name: KoderWiki
description: Let's gather all my knowledge in one place
meta_description: "KoderWiki, Let's gather all my knowledge in one place"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: "http://Koderwiki.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Kogeonu"

# Disqus config
disqus-shortname: ""
